name: Tests

on: [push, pull_request]

env:
  RELEASE: 0
  artifact: 0

jobs:  
  linux_test:
    name: Linux Unit Tests [TEST_USE_ROCKSDB=${{ matrix.TEST_USE_ROCKSDB }} - COMPILER=${{ matrix.COMPILER }}]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        TEST_USE_ROCKSDB: [0, 1]
        COMPILER: [gcc, clang-6]
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-20.04
    env:
      COMPILER: ${{ matrix.COMPILER }}
      TEST_USE_ROCKSDB: ${{ matrix.TEST_USE_ROCKSDB }}
      RELEASE: ${{ matrix.RELEASE }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      # Update references
      - name: Git Sumbodule Update
        run: git submodule update --init --recursive
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Build Tests
        run: docker run -e TEST_USE_ROCKSDB  -e RELEASE -v ${PWD}:/workspace nanocurrency/nano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace && TSAN=1 ./ci/build-ci.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5"
      - name: Run Tests lmdb
        if: ${{ matrix.TEST_USE_ROCKSDB == 0 }}
        run: docker run  -e RELEASE -v ${PWD}:/workspace nanocurrency/nano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace/build && TSAN_OPTIONS=suppressions="./ci/suppressions/tsan_suppressions":log_exe_name=1:log_path="./tsan_report" ./core_test"
      - name: Run Tests rocksdb
        if: ${{ matrix.TEST_USE_ROCKSDB == 1 }}
        run: docker run -e TEST_USE_ROCKSDB -e DEADLINE_SCALE_FACTOR=2  -e RELEASE -v ${PWD}:/workspace nanocurrency/nano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace/build && TSAN_OPTIONS=suppressions="./ci/suppressions/tsan_suppressions":log_exe_name=1:log_path="./tsan_report" ./core_test"
